### ISSUE TITLE
Not showing in the controls tab

### ISSUE THREAD

**Issue by tarikcosovic** [drivardxrm/TimePicker.PCF#1]
On one of my solutions the time-picker is working just fine and on the other one it is imported successfully, but it is not showing in my controls tab when I want to select it, also the field that I am using is a 'DateTime' field.

At first I tried the unmanaged solution, because my working-solution is also unmanaged type and then when I didn't know what else to do I tried the managed solution which had no effect also.

![83076009_620512555382586_4880898021694373888_n](https://user-images.githubusercontent.com/16970439/73485047-b80f6100-43a2-11ea-875f-f07870692165.png)

**Comment by drivardxrm** [comment]
Hi Tarik,  the control is meant to be used with a Integer (Whole number) field. It is **not designed to be bound to a DateTime** field. In fact, you need 2 backend integer field. 1 that will store the hours part, 1 that will store the minutes part.  

If you choose a whole number field and try to add the control, you should see it.

**Comment by tarikcosovic** [comment]
Yeah I realize that, but somehow I have managed to bind it to a DateTime field in my previous solution..

**Comment by drivardxrm** [comment]
That is impossible, if you look at the code (manifest file), it only accepts fields of type (Whole.None)

**Comment by tarikcosovic** [comment]
Seems that in my previous solution I used TimeWithoutDate, which I assume is not your time picker?

![image](https://user-images.githubusercontent.com/16970439/73495236-6d97df80-43b6-11ea-9983-3e882b745380.png)

**Comment by tarikcosovic** [comment]
Just switched to time-picker, it works fine, that was a silly mistake and thanks for your help!
