### ISSUE TITLE
How to use this solution from managed package? 

### ISSUE THREAD

**Issue by MateRadz** [drivardxrm/TimePicker.PCF#15]
Hi I am new to PCF controls and I just want to enable it in customised Dynamics 365 for sales. I installed the managed package. And what next? Should this be available on the form?

**Comment by drivardxrm** [comment]
Hi @MateRadz thanks for your interest in the control.

The control is bound on 2 whole number fields (integers)
So you need to have a field that will hold the hours and a field that will hold the minutes.

Once your 2 fields are defined on your entity you can go and edit your Form.

Unfortunately, the PCF capabilities are not yet working in the new Form editor so you will have to switch to classic.
![image](https://user-images.githubusercontent.com/38399134/102518175-f10a0000-405e-11eb-8115-e2c450a44725.png)

In the classic mode, just drop the field for the hours and go in the properties.
In the controls tab, go to Add Controls, you should See the TimePicker control available

![image](https://user-images.githubusercontent.com/38399134/102518551-6d9cde80-405f-11eb-9169-6fd25bae306f.png)

Once the control is added, you can configure and enable it

![image](https://user-images.githubusercontent.com/38399134/102518803-bbb1e200-405f-11eb-9ec8-8e9859c10413.png)

You should be good to go

Hope this helps
