### ISSUE TITLE
Unable to access V1.0 managed solution download

### ISSUE THREAD

**Issue by DeadDuck** [drivardxrm/TimePicker.PCF#2]
I needed this version in order to import a solution with dependencies, however the link to the blob give 404 error.

**Comment by drivardxrm** [comment]
Hi, you can download the solution to import on the Release tab of the repository 
![image](https://user-images.githubusercontent.com/38399134/75379211-011fdb80-58a3-11ea-94c1-bd31c7cfab32.png)

**Comment by drivardxrm** [comment]
You should reimport this new solution and relink to the new control. (I had to change the namespace)

**Comment by DeadDuck** [comment]
Thanks for your reply. This was an existing export file complaining about the missing component. Now I'm taking a new export from the updated source environment.

Readme still has the broken links btw.

Thanks for sharing!

**Comment by drivardxrm** [comment]
Thanks, I will fix the readme ;)
