### ISSUE TITLE
Cannot edit the Hour Value Field

### ISSUE THREAD

**Issue by themuls** [drivardxrm/TimePicker.PCF#3]
Hello David,

Firstly thanks for developing this and providing it to the public.

I am having a small problem with it that is a show-stopper. I may be missing something obvious here but I’m at a loss to find it.

I have three whole number fields on my form:

•	Start Time to which I bound the PCF Timer Picker Control.
•	Start Time Hours to hold the number of hours
•	Start Time Minutes to hold the number of minutes

I bind the PCF Timer control to the Start Time; unfortunately, the Hour Value property cannot be edited and binds itself to the Start Time which is the very field the control is bound to.

The Minute Value Field is editable so correctly displays the number of minutes selected in the PCF Timer.

Images are below.

What am I not getting here?

![image](https://user-images.githubusercontent.com/10472800/75984037-6de74580-5f35-11ea-9715-8ac97d6b7894.png)

![image](https://user-images.githubusercontent.com/10472800/75984153-996a3000-5f35-11ea-9136-0e9e14562414.png)

**Comment by drivardxrm** [comment]
Hi, you don't need the 'Start Time' field. You need to bind Hour parameter to the 'Start Time Hours Field' (This would be your main field on which you define the control) and the Minute parameter would be bound to the 'Start Time Minute'.   If you really want to see the result, you can then duplicate the 'Start Time Hours' field on the form.   Glad you like the control.

**Comment by themuls** [comment]
Thanks for your swift and accurate response – yes that indeed was my issue and it works fine.

Well done to you by the way.

Not to be a nuisance, but I do note that the clear ‘x’ on the control deletes the control – or renders it invisible such that the user cannot enter data anymore until the form is refreshed. Not a show-stopper but a little disconcerting to a user.
 
![image](https://user-images.githubusercontent.com/10472800/76029713-c3950f80-5f80-11ea-8716-e25b4389f216.png)

**Comment by drivardxrm** [comment]
Hi @themuls, 
Great to see that you managed to make it work.
Thanks for the feedback, I will correct the bug you mentioned and publish a new release soon.

**Comment by drivardxrm** [comment]
Hi @themuls ,
I just released a new version, that fixes the bug
https://github.com/drivardxrm/TimePicker.PCF/releases/tag/v1.0.0.3

**Comment by themuls** [comment]
Yep, that did the trick, thank you again.

If you would like me to donate a little something for your efforts or to your favourite charity or open source vendor then I am happy to oblige.

**Comment by RugerSR762** [comment]
Good afternoon - agree with themuls, great control.  Is there anything specific you need to do in order to render this in a view?   For example, I entered (selected) 9:30AM, however the view shows 30:

![image](https://user-images.githubusercontent.com/48356164/77699865-8de4b480-6f89-11ea-8542-147f08391ff5.png)

**Comment by themuls** [comment]
Hi,
As a courtesy, I need to advise you that the control does not display the time if I open an exiting record even though the time (hours and minutes) exists,

![image](https://user-images.githubusercontent.com/10472800/77879751-d44a5400-72a6-11ea-9aff-1d728aef1fec.png)

Thanks again though for your efforts.

**Comment by drivardxrm** [comment]
@themuls Can you share the configuration of the PCF ? Can you show me the real values (No PCF) that way I could try to reproduce the issue.

**Comment by drivardxrm** [comment]
@RugerSR762 the control is not meant for views. If you want to display the time value in a view, maybe you could try to have a calculated field that concatenates the 2 values ex ("[hour]:[minutes]").

**Comment by themuls** [comment]
@RugerSR762 re the views, I did exactly  as @drivardxrm  advised and it works fine.

**Comment by themuls** [comment]
> @RugerSR762 the control is not meant for views. If you want to display the time value in a view, maybe you could try to have a calculated field that concatenates the 2 values ex ("[hour]:[minutes]").

Saved record:
![image](https://user-images.githubusercontent.com/10472800/77991362-04592c00-7367-11ea-80cc-1b551acbc6da.png)

In the view:
![image](https://user-images.githubusercontent.com/10472800/77991409-26eb4500-7367-11ea-95fe-7d4cbedc13ae.png)

Reopened from the view:
![image](https://user-images.githubusercontent.com/10472800/77991475-4edaa880-7367-11ea-95d2-82c88fd38fec.png)

Refreshed (pressed F5):
![image](https://user-images.githubusercontent.com/10472800/77991511-6c0f7700-7367-11ea-821d-f3cf4929aecf.png)

Display no PCF:

**Comment by RugerSR762** [comment]
Hey guys thanks for your responses.  Makes sense!

**Comment by drivardxrm** [comment]
@themuls there is definitely a bug here. I will correct the situation soon and let you know when a new release is available.

**Comment by RugerSR762** [comment]
Thanks @drivardxrm.   In the meantime, the concatenation solution/workaround seems like it should do the job for now.  Definitely look forward to new releases as I can see this control being used in other builds.

**Comment by drivardxrm** [comment]
@themuls @RugerSR762 I just released a new version that fixes the bug mentioned.
[https://github.com/drivardxrm/TimePicker.PCF/releases/tag/v1.0.0.4](url)

**Comment by themuls** [comment]
Hi drivardxrm

Apologies for my late response and again thank you for your efforts. 

I haven't implemented your control because the client changed the requirement anyway and wanted the hours separate from the days. But I wll jeep it in mind for the future because it is a pretty good - and useful - control.
