### ISSUE TITLE
Rendering issue with the Minute selected in 0 mins.

### ISSUE THREAD

**Issue by chetanhiran** [drivardxrm/TimePicker.PCF#5]
Senario: Pick the time as 7:00 hrs. Save the record. Refresh the form, the attribute values are not displayed.
The issue occurs only when the selected minute is 0.

**Comment by drivardxrm** [comment]
@chetanhiran I will have a look at this ASAP. thanks for the catch

**Comment by drivardxrm** [comment]
@chetanhiran just released version 1.0.0.5 that fixes the bug
[https://github.com/drivardxrm/TimePicker.PCF/releases/tag/v1.0.0.5](url)
